name: Build and Test
on: pull_request
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Pull source code
      uses: actions/checkout@v3
    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: Build with Gradle
      run: $GITHUB_WORKSPACE/gradlew build

    - name: Upload JARs & reports
      uses: actions/upload-artifact@v3
      with:
        name: Test report
        path: |
          ./build/reports/
          ./build/libs/
        if-no-files-found: error
        retention-days: 2
