name: Build and Test
on: pull_request
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: Pull source code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: set up jdk 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Enable Gradle
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: reports_${GITHUB_SHA}
        path: ./build/reports/
        if-no-files-found: error
        retention-days: 1

    - name: Pull Karate Standalone JAR from cache
      id: karate-cache
      uses: actions/cache/restore@v3
      with:
        path: karate
        key: karate-jar

    - name: Pull Karate Standalone JAR on cache miss
      if: steps.karate-cache.outputs.cache-hit != 'true'
      run: mkrdir -p ./karate

    - name: Pull Karate Standalone JAR on cache miss
      if: steps.karate-cache.outputs.cache-hit != 'true'
      uses: wei/wget@v1
      with:
        args: -O ./karate/karate.jar https://github.com/karatelabs/karate/releases/download/v1.4.0/karate-1.4.0.jar

    - name: Cache Karate Standalone JAR on cache miss
      if: steps.karate-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: karate
        key: karate-jar

      # build docker container
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        file: ./docker/app/Dockerfile
        context: .
        load: true
        tags: local-test

    - name: Start Test Containers
      run: |
        docker-compose up -d app-pipeline
        sleep 20

    - name: Run Karate Tests
      run: java -jar karate.jar -T 5 -o ./build/reports/karate ./src/test/karate/features