name: End to End Test
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

env:
  TEST_TAG: snalesh/cookbook-recipes-service:test
  LATEST_TAG: snalesh/cookbook-recipes-service:latest

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      # Prepare runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up jre 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jre

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # load required files
      - name: Pull App JARs
        uses: actions/download-artifact@v3
        with:
          name: jars_${GITHUB_SHA}
          path: ./build/libs/

      - name: Pull Karate Standalone JAR from cache
        id: karate-cache
        uses: actions/cache/restore@v3
        with:
          key: karate-jar

      - name: Pull Karate Standalone JAR on cache miss
        if: steps.karate-cache.outputs.cache-hit != 'true'
        uses: wei/wget@v1
        with:
          args: -O karate.jar https://github.com/karatelabs/karate/releases/download/v1.4.0/karate-1.4.0.jar

      - name: Cache Karate Standalone JAR on cache miss
        if: steps.karate-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: karate.jar
          key: karate-jar

      # build docker container
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          file: ./docker/app/Dockerfile
          context: .
          load: true
          tags: local-test

      - name: Start Test Containers
        run: |
          docker-compose up -d app-pipeline
          sleep 20

      - name: Run Karate Tests
        run: java -jar karate.jar -T 5 -o ./build/reports/karate ./src/test/karate/features